jwt = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL2V4YW1wbGUuY29tL2NvdW50cnkiOiJVbml0ZWQgU3RhdGVzIiwiaHR0cHM6Ly9leGFtcGxlLmNvbS90aW1lem9uZSI6IkFtZXJpY2EvTG9zX0FuZ2VsZXMiLCJodHRwczovL2V4YW1wbGUuY29tL2dlb2lwIjp7ImNvdW50cnlfY29kZSI6IlVTIiwiY291bnRyeV9jb2RlMyI6IlVTQSIsImNvdW50cnlfbmFtZSI6IlVuaXRlZCBTdGF0ZXMiLCJjaXR5X25hbWUiOiJTYW50YSBBbmEiLCJsYXRpdHVkZSI6MzMuNzQ5OSwibG9uZ2l0dWRlIjotMTE3LjkwNzEsInRpbWVfem9uZSI6IkFtZXJpY2EvTG9zX0FuZ2VsZXMiLCJjb250aW5lbnRfY29kZSI6Ik5BIiwic3ViZGl2aXNpb25fY29kZSI6IkNBIiwic3ViZGl2aXNpb25fbmFtZSI6IkNhbGlmb3JuaWEifSwibmlja25hbWUiOiJkdG5ndXkwOSIsIm5hbWUiOiJkdG5ndXkwOUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvNTZjY2EzMmUxMjU3NmY3NWFkNjBiOGIyZTM5NThhM2U_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZkdC5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyMy0xMi0yNVQyMTo1MDoyNy4xOTBaIiwiZW1haWwiOiJkdG5ndXkwOUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9ib290bW9kMy5hdXRoMC5jb20vIiwiYXVkIjoiakZDc0YyUkpleGliVDVSaGJUQ25Rc0QxRTdodFM5R1QiLCJpYXQiOjE3MDM1NDEwMjgsImV4cCI6MTczNTA3NzAyOCwic3ViIjoiYXV0aDB8NjU4NjA3NzQ3OTI1Njg4ZWNmMTdiNDM4IiwiYXRfaGFzaCI6Imh6MXlTNWlwREJzVExmeHpWbnI1dWciLCJub25jZSI6IkxTUWF5UW1Zc2s1YXVkdEZJZVhrc3cuOWsyLmw2bFQ5In0.TR2p43oHxwT79HnLIhQ5uyY62zfoQUy8mqSQ9TGOeoI'

test_response =["0.000","5814+0","5801+0.0","4205+0.0","4536+14.7","4AB0+0.0","5805+59","5819+0","5881+0","56C1+-14","56D7+113","580F+63","580E+0.0","4A49+-0.1","4A4A+-0.1","4A4C+-0.1","4A4D+-0.1","4A4E+-0.1","4A4F+-0.1","4A36+0","58F3+72","5807+1.00","582C+10.29","5889+19.11","5804+0.0","5813+63.0","5818+0.0","5812+0.0","580B+0.0","5806+1.00","4600+23","580D+0","4AAB+50","6001CFF8+12.18","60001C0C+-1.339","6000251C+1.000","60002530+1.000","60003648+0.0","60003B56+0.000","60003B58+0.000","60003B5A+0.000","60003B5C+0.000","60003B5E+0.000","60003B60+0.000","6000344C+0.0000","60001CA8+184.20","600031D4+184.2000","50004DC8+0","600017B8+0.00","600017B4+0.00","600017BC+0.00","60003006+0.00","60002E4E+0.000","60002CC4+-38.8","600024DE+3.99993","60038090+0","6003814A+0.00","60038149+0.00","6003814B+0.63","60038096+38","60038140+38","60038141+77","60038147+0","60038082+0.00","6003808E+0.00","60038084+0.00","60038006+1"]


big_payload = {
  "diagRequestType": "STREAM",
  "requestId": "1703710588333",
  "deviceId": "WZ1DB0G05PW056302",
  "userId": "WZ1DB0G05PW056302",
  "channelList": [
    {
      "high": False,
      "signed": False,
      "pid": "6001CFF8",
      "name": "(RAM) Battery Voltage",
      "units": "V",
      "unitsImp": "V",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned integer",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 5,
      "minValImp": 0,
      "maxValImp": 5,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "V",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          1,
          -6,
          0,
          0,
          0.00025
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "V"
    },
    {
      "high": False,
      "signed": False,
      "pid": "60001C0C",
      "name": "(RAM) Boost Pressure (Target)",
      "units": "hPa",
      "unitsImp": "psia",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned integer",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 8191.875,
      "minValImp": 0,
      "maxValImp": 118.782,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "hPa",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          8,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "psig"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5822",
      "name": "Oil temperature",
      "units": "C",
      "unitsImp": "F",
      "ram": False,
      "factor": "1.0",
      "div": "1.0",
      "add": "-60.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": True,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": -10000,
      "maxVal": 10000,
      "minValImp": -17968,
      "maxValImp": 18032,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0
    },
    {
      "high": False,
      "signed": False,
      "pid": "60002530",
      "name": "(RAM) Boost Setpoint",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned integer",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 10,
      "minValImp": 0,
      "maxValImp": 10,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          8192,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": False,
      "pid": "6000251C",
      "name": "(RAM) Boost Setpoint",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned integer",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 10,
      "minValImp": 0,
      "maxValImp": 10,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          8192,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60003648",
      "name": "(RAM) Ignition Timing Corr. (Total)",
      "units": "··",
      "unitsImp": "··",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -3276.8,
      "maxValImp": 3276.7,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "··",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "··"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60003B56",
      "name": "(RAM) Ignition Timing Corr. Cyl. 1",
      "units": "··",
      "unitsImp": "··",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "valIdx": 0,
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -3276.8,
      "maxValImp": 3276.7,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "··",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "··"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60003B58",
      "name": "(RAM) Ignition Timing Corr. Cyl. 2",
      "units": "··",
      "unitsImp": "··",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "valIdx": 1,
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -3276.8,
      "maxValImp": 3276.7,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "··",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "··"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60003B5A",
      "name": "(RAM) Ignition Timing Corr. Cyl. 3",
      "units": "··",
      "unitsImp": "··",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "valIdx": 2,
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -3276.8,
      "maxValImp": 3276.7,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "··",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "··"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60003B5C",
      "name": "(RAM) Ignition Timing Corr. Cyl. 4",
      "units": "··",
      "unitsImp": "··",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "valIdx": 3,
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -3276.8,
      "maxValImp": 3276.7,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "··",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "··"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60003B5E",
      "name": "(RAM) Ignition Timing Corr. Cyl. 5",
      "units": "··",
      "unitsImp": "··",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "valIdx": 4,
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -3276.8,
      "maxValImp": 3276.7,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "··",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "··"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60003B60",
      "name": "(RAM) Ignition Timing Corr. Cyl. 6",
      "units": "··",
      "unitsImp": "··",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "valIdx": 5,
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -3276.8,
      "maxValImp": 3276.7,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "··",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "··"
    },
    {
      "high": False,
      "signed": True,
      "pid": "6000344C",
      "name": "(RAM) Load (Actual)",
      "units": "%",
      "unitsImp": "%",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -327.68,
      "maxVal": 327.67,
      "minValImp": -327.68,
      "maxValImp": 327.67,
      "invalid": False,
      "isHigh": False,
      "precision": 4,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "%",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          100,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60001CA8",
      "name": "(RAM) Load (Limit)",
      "units": "%",
      "unitsImp": "%",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -327.68,
      "maxVal": 327.67,
      "minValImp": -327.68,
      "maxValImp": 327.67,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "%",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          100,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    },
    {
      "high": False,
      "signed": True,
      "pid": "600031D4",
      "name": "(RAM) Load (Target)",
      "units": "%",
      "unitsImp": "%",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -327.68,
      "maxVal": 327.67,
      "minValImp": -327.68,
      "maxValImp": 327.67,
      "invalid": False,
      "isHigh": False,
      "precision": 4,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "%",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          100,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    },
    {
      "high": False,
      "signed": False,
      "pid": "50004DC8",
      "name": "(RAM) Torque Limit (Flag)",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned long",
      "bytes": 4,
      "minVal": 0,
      "maxVal": 4294967295,
      "minValImp": 0,
      "maxValImp": 4294967295,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          1,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": False,
      "pid": "600017B8",
      "name": "(RAM) Torque Limit Active (Flag)",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned long",
      "bytes": 4,
      "minVal": 0,
      "maxVal": 536870912,
      "minValImp": 0,
      "maxValImp": 536870912,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "TAB_VERB",
        "format": "%6.3",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": "ubzEiqb_cvaCBwb_aEdiltc_nDUAL3P",
        "coeffs": None
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": False,
      "pid": "600017B4",
      "name": "(RAM) Torque Limit Active 2 (Flag)",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned long",
      "bytes": 4,
      "minVal": 0,
      "maxVal": 536870912,
      "minValImp": 0,
      "maxValImp": 536870912,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "TAB_VERB",
        "format": "%6.3",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": "ubzEiqb_cvaCBwb_aEdiltc_nDUAL3P",
        "coeffs": None
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": False,
      "pid": "600017BC",
      "name": "(RAM) Torque Limit Active 3 (Flag)",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned long",
      "bytes": 4,
      "minVal": 0,
      "maxVal": 536870912,
      "minValImp": 0,
      "maxValImp": 536870912,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "TAB_VERB",
        "format": "%6.3",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": "ubzEiqb_cvaCBwb_aEdiltc_nDUAL3P",
        "coeffs": None
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60003006",
      "name": "(RAM) Torque at Clutch (Actual)",
      "units": "Nm",
      "unitsImp": "lb/ft",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -2416.84,
      "maxValImp": 2416.77,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "Nm",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "Nm"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60002E4E",
      "name": "(RAM) Torque at Clutch (Target)",
      "units": "Nm",
      "unitsImp": "lb/ft",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -2416.844,
      "maxValImp": 2416.77,
      "invalid": False,
      "isHigh": False,
      "precision": 3,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "Nm",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "Nm"
    },
    {
      "high": False,
      "signed": True,
      "pid": "60002CC4",
      "name": "(RAM) Torque at Clutch (Target) (Pre-DrivDynmcs)",
      "units": "Nm",
      "unitsImp": "lb/ft",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed integer",
      "bytes": 2,
      "minVal": -3276.8,
      "maxVal": 3276.7,
      "minValImp": -2416.8,
      "maxValImp": 2416.8,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "Nm",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          10,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "Nm"
    },
    {
      "high": False,
      "signed": False,
      "pid": "600024DE",
      "name": "(RAM) Turbine Distribution Factor (Turbine/Wastegate)",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned integer",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 3.99993896484375,
      "minValImp": 0,
      "maxValImp": 3.99994,
      "invalid": False,
      "isHigh": False,
      "precision": 5,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.3",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          16384,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": True,
      "pid": "5814",
      "name": "Accel. Pedal",
      "units": "%",
      "unitsImp": "%",
      "ram": False,
      "factor": "0.01220703",
      "div": "1.0",
      "add": "0.0",
      "def": False,
      "defDash": False,
      "required": True,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 100,
      "minValImp": 0,
      "maxValImp": 100,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5801",
      "name": "Ambient pressure",
      "units": "hPa",
      "unitsImp": "psia",
      "ram": False,
      "factor": "0.0390625",
      "div": "1.0",
      "add": "0.0",
      "def": False,
      "defDash": False,
      "required": True,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 5000,
      "minValImp": 0,
      "maxValImp": 72.5,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "psig"
    },
    {
      "high": False,
      "signed": False,
      "pid": "60038090",
      "name": "BM3 Antilag Active",
      "units": "",
      "unitsImp": "",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 255,
      "minValImp": 0,
      "maxValImp": 255,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.2",
        "unit": "",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          1,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": ""
    },
    {
      "high": False,
      "signed": False,
      "pid": "6003814A",
      "name": "BM3 Flex Blend Factor (Fuel)",
      "units": "",
      "unitsImp": "",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 255,
      "minValImp": 0,
      "maxValImp": 255,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.2",
        "unit": "",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          255,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": ""
    },
    {
      "high": False,
      "signed": False,
      "pid": "60038149",
      "name": "BM3 Flex Blend Factor (Ign.)",
      "units": "",
      "unitsImp": "",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 255,
      "minValImp": 0,
      "maxValImp": 255,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.2",
        "unit": "",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          255,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": ""
    },
    {
      "high": False,
      "signed": False,
      "pid": "6003814B",
      "name": "BM3 Flex Blend Factor (Trq.)",
      "units": "",
      "unitsImp": "",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 255,
      "minValImp": 0,
      "maxValImp": 255,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.2",
        "unit": "",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          255,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": ""
    },
    {
      "high": False,
      "signed": False,
      "pid": "60038096",
      "name": "BM3 Flex Ethanol %",
      "units": "%",
      "unitsImp": "%",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 255,
      "minValImp": 0,
      "maxValImp": 255,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.2",
        "unit": "%",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          1,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    },
    {
      "high": False,
      "signed": False,
      "pid": "60038140",
      "name": "BM3 Flex Ethanol % (Sensor)",
      "units": "%",
      "unitsImp": "%",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 255,
      "minValImp": 0,
      "maxValImp": 255,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.2",
        "unit": "%",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          1,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    },
    {
      "high": False,
      "signed": False,
      "pid": "60038141",
      "name": "BM3 Flex Fuel Temp",
      "units": "C",
      "unitsImp": "F",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 255,
      "minValImp": 32,
      "maxValImp": 491,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.2",
        "unit": "C",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          1,
          40,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "F"
    },
    {
      "high": False,
      "signed": False,
      "pid": "60038147",
      "name": "BM3 Flex Sensor Fault",
      "units": "",
      "unitsImp": "",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 255,
      "minValImp": 0,
      "maxValImp": 255,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.2",
        "unit": "",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          1,
          0,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": ""
    },
    {
      "high": False,
      "signed": False,
      "pid": "60038082",
      "name": "BM3 Fuel Corr. (Base)",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned integer",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 1.999969,
      "minValImp": 0,
      "maxValImp": 2,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%7.6",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          65536,
          0,
          0,
          0,
          2
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": False,
      "pid": "6003808E",
      "name": "BM3 Fuel Corr. (Final)",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned integer",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 1.999969,
      "minValImp": 0,
      "maxValImp": 2,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%7.6",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          65536,
          0,
          0,
          0,
          2
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": False,
      "pid": "60038084",
      "name": "BM3 Fuel Corr. (Flex Adder)",
      "units": "-",
      "unitsImp": "-",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned integer",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 1.999969,
      "minValImp": 0,
      "maxValImp": 2,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%7.6",
        "unit": "-",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          65536,
          0,
          0,
          0,
          2
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": False,
      "pid": "60038006",
      "name": "BM3 Map Slot",
      "units": "",
      "unitsImp": "",
      "ram": True,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 255,
      "minValImp": 0,
      "maxValImp": 255,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "cm": {
        "type": "RAT_FUNC",
        "format": "%6.2",
        "unit": "",
        "bigEndian": False,
        "refcomputab": None,
        "coeffs": [
          0,
          1,
          -1,
          0,
          0,
          1
        ]
      },
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": ""
    },
    {
      "high": False,
      "signed": False,
      "pid": "4205",
      "name": "Boost (Pre-Throttle)",
      "units": "hPa",
      "unitsImp": "psia",
      "ram": False,
      "factor": "20.0",
      "div": "256.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": True,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 5000,
      "minValImp": 0,
      "maxValImp": 72.5,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": 0,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "defGaugeSize": "L",
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "psig"
    },
    {
      "high": False,
      "signed": True,
      "pid": "4536",
      "name": "Boost Pressure (Deviation)",
      "units": "hPa",
      "unitsImp": "psia",
      "ram": False,
      "factor": "125.0",
      "div": "1000.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 5000,
      "minValImp": 0,
      "maxValImp": 72.5,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": True,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "psig"
    },
    {
      "high": False,
      "signed": False,
      "pid": "4AB0",
      "name": "Boost pressure (Target)",
      "units": "hPa",
      "unitsImp": "psia",
      "ram": False,
      "factor": "10.0",
      "div": "256.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 5000,
      "minValImp": 0,
      "maxValImp": 72.5,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "psig"
    },
    {
      "high": False,
      "signed": True,
      "pid": "5805",
      "name": "Coolant Temp",
      "units": "C",
      "unitsImp": "F",
      "ram": False,
      "factor": "0.1",
      "div": "1.0",
      "add": "-273.14",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": -30,
      "maxVal": 130,
      "minValImp": -22,
      "maxValImp": 266,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "F"
    },
    {
      "high": False,
      "signed": True,
      "pid": "5819",
      "name": "Engine speed",
      "units": "1/min",
      "unitsImp": "1/min",
      "ram": False,
      "factor": "1.0",
      "div": "2.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": True,
      "type": "signed int",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 8000,
      "minValImp": 0,
      "maxValImp": 8000,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": 1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "RPM"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5881",
      "name": "Gear",
      "units": "-",
      "unitsImp": "-",
      "ram": False,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 8,
      "minValImp": 0,
      "maxValImp": 8,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": False,
      "pid": "56C1",
      "name": "HPFP (Target)",
      "units": "MPa",
      "unitsImp": "psia",
      "ram": False,
      "factor": "0.002",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": -10000,
      "maxVal": 10000,
      "minValImp": -1450000,
      "maxValImp": 1450000,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "psig"
    },
    {
      "high": False,
      "signed": False,
      "pid": "56D7",
      "name": "HPFP Act.",
      "units": "MPa",
      "unitsImp": "psia",
      "ram": False,
      "factor": "0.002",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": -10000,
      "maxVal": 10000,
      "minValImp": -1450000,
      "maxValImp": 1450000,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "psig"
    },
    {
      "high": False,
      "signed": False,
      "pid": "580F",
      "name": "IAT",
      "units": "C",
      "unitsImp": "F",
      "ram": False,
      "factor": "0.75",
      "div": "1.0",
      "add": "-48.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": True,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": -30,
      "maxVal": 130,
      "minValImp": -22,
      "maxValImp": 266,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": 2,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "F"
    },
    {
      "high": False,
      "signed": True,
      "pid": "580E",
      "name": "Ignition Cyl 1",
      "units": "deg",
      "unitsImp": "deg",
      "ram": False,
      "factor": "191.25",
      "div": "255.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": True,
      "type": "signed char",
      "bytes": 1,
      "minVal": -60,
      "maxVal": 60,
      "minValImp": -60,
      "maxValImp": 60,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": 3,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "deg"
    },
    {
      "high": False,
      "signed": True,
      "pid": "4A49",
      "name": "Ignition Timing 1",
      "units": "deg",
      "unitsImp": "deg",
      "ram": False,
      "factor": "1.0",
      "div": "10.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": -60,
      "maxVal": 60,
      "minValImp": -60,
      "maxValImp": 60,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "deg"
    },
    {
      "high": False,
      "signed": True,
      "pid": "4A4A",
      "name": "Ignition Timing 2",
      "units": "deg",
      "unitsImp": "deg",
      "ram": False,
      "factor": "1.0",
      "div": "10.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": -60,
      "maxVal": 60,
      "minValImp": -60,
      "maxValImp": 60,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "deg"
    },
    {
      "high": False,
      "signed": True,
      "pid": "4A4C",
      "name": "Ignition Timing 3",
      "units": "deg",
      "unitsImp": "deg",
      "ram": False,
      "factor": "1.0",
      "div": "10.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": -60,
      "maxVal": 60,
      "minValImp": -60,
      "maxValImp": 60,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "deg"
    },
    {
      "high": False,
      "signed": True,
      "pid": "4A4D",
      "name": "Ignition Timing 4",
      "units": "deg",
      "unitsImp": "deg",
      "ram": False,
      "factor": "1.0",
      "div": "10.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": -60,
      "maxVal": 60,
      "minValImp": -60,
      "maxValImp": 60,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "deg"
    },
    {
      "high": False,
      "signed": True,
      "pid": "4A4E",
      "name": "Ignition Timing 5",
      "units": "deg",
      "unitsImp": "deg",
      "ram": False,
      "factor": "1.0",
      "div": "10.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": -60,
      "maxVal": 60,
      "minValImp": -60,
      "maxValImp": 60,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "deg"
    },
    {
      "high": False,
      "signed": True,
      "pid": "4A4F",
      "name": "Ignition Timing 6",
      "units": "deg",
      "unitsImp": "deg",
      "ram": False,
      "factor": "1.0",
      "div": "10.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": -60,
      "maxVal": 60,
      "minValImp": -60,
      "maxValImp": 60,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "deg"
    },
    {
      "high": False,
      "signed": False,
      "pid": "4A36",
      "name": "Knock Detected",
      "units": "0-n",
      "unitsImp": "0-n",
      "ram": False,
      "factor": "1.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 1,
      "minValImp": 0,
      "maxValImp": 1,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "0-n"
    },
    {
      "high": False,
      "signed": False,
      "pid": "58F3",
      "name": "LPFP Act. (Raw)",
      "units": "kPa",
      "unitsImp": "psia",
      "ram": False,
      "factor": "1.0",
      "div": "10.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": -10000,
      "maxVal": 10000,
      "minValImp": -1450,
      "maxValImp": 1450,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "psig"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5807",
      "name": "LTFT",
      "units": "-",
      "unitsImp": "-",
      "ram": False,
      "factor": "2.0",
      "div": "65536.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": 0.7,
      "maxVal": 1.3,
      "minValImp": 0.7,
      "maxValImp": 1.3,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": False,
      "pid": "582C",
      "name": "Lambda",
      "units": "AFR",
      "unitsImp": "··",
      "ram": False,
      "factor": "16.0",
      "div": "65536.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": True,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": 0.7,
      "maxVal": 1.3,
      "minValImp": 10.29,
      "maxValImp": 19.11,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": 4,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "AFR"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5889",
      "name": "Lambda Act.",
      "units": "AFR",
      "unitsImp": "··",
      "ram": False,
      "factor": "16.0",
      "div": "65536.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": 0.7,
      "maxVal": 1.3,
      "minValImp": 10.29,
      "maxValImp": 19.11,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "AFR"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5804",
      "name": "Load Act. (Rel.)",
      "units": "%",
      "unitsImp": "%",
      "ram": False,
      "factor": "100.0",
      "div": "256.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 370,
      "minValImp": 0,
      "maxValImp": 370,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5813",
      "name": "Load Target (Rel.)",
      "units": "%",
      "unitsImp": "%",
      "ram": False,
      "factor": "0.75",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 370,
      "minValImp": 0,
      "maxValImp": 370,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5818",
      "name": "MAF",
      "units": "kg/h",
      "unitsImp": "lb/min",
      "ram": False,
      "factor": "4.0",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": True,
      "type": "unsigned char",
      "bytes": 1,
      "minVal": 0,
      "maxVal": 10000,
      "minValImp": 0,
      "maxValImp": 367.4,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "kg/h"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5812",
      "name": "MAF HFM",
      "units": "kg/h",
      "unitsImp": "lb/min",
      "ram": False,
      "factor": "0.1",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 10000,
      "minValImp": 0,
      "maxValImp": 367.4,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "kg/h"
    },
    {
      "high": False,
      "signed": False,
      "pid": "580B",
      "name": "MAP",
      "units": "hPa",
      "unitsImp": "psia",
      "ram": False,
      "factor": "10.0",
      "div": "256.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 5000,
      "minValImp": 0,
      "maxValImp": 72.5,
      "invalid": False,
      "isHigh": False,
      "precision": 1,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "psig"
    },
    {
      "high": False,
      "signed": False,
      "pid": "5806",
      "name": "STFT",
      "units": "-",
      "unitsImp": "-",
      "ram": False,
      "factor": "2.0",
      "div": "65536.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": 0.7,
      "maxVal": 1.3,
      "minValImp": 0.7,
      "maxValImp": 1.3,
      "invalid": False,
      "isHigh": False,
      "precision": 2,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "-"
    },
    {
      "high": False,
      "signed": True,
      "pid": "4600",
      "name": "Throttle Angle",
      "units": "%",
      "unitsImp": "%",
      "ram": False,
      "factor": "0.0078125",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": True,
      "required": False,
      "selected": True,
      "showInDash": True,
      "type": "signed int",
      "bytes": 2,
      "minVal": 0,
      "maxVal": 100,
      "minValImp": 0,
      "maxValImp": 100,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": 5,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    },
    {
      "high": False,
      "signed": True,
      "pid": "580D",
      "name": "Vehicle Speed",
      "units": "km/h",
      "unitsImp": "mph",
      "ram": False,
      "factor": "0.01",
      "div": "1.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "signed int",
      "bytes": 2,
      "minVal": -10000,
      "maxVal": 10000,
      "minValImp": -6214,
      "maxValImp": 6214,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "mph"
    },
    {
      "high": False,
      "signed": False,
      "pid": "4AAB",
      "name": "WGDC",
      "units": "%",
      "unitsImp": "%",
      "ram": False,
      "factor": "100.0",
      "div": "65536.0",
      "add": "0.0",
      "def": True,
      "defDash": False,
      "required": False,
      "selected": True,
      "showInDash": False,
      "type": "unsigned int",
      "bytes": 2,
      "minVal": -10000,
      "maxVal": 10000,
      "minValImp": -10000,
      "maxValImp": 10000,
      "invalid": False,
      "isHigh": False,
      "precision": 0,
      "refreshRate": 0,
      "order": -1,
      "radiusScale": 1,
      "lineThickness": 0.05,
      "forceAbsolute": False,
      "angle": -0.29,
      "colorStart": "#e6001b",
      "strokeColor": "#292929",
      "pointerColor": "#F6532D",
      "pointerStrokeWidth": 0,
      "pointerLength": 0,
      "maxPeakVal": None,
      "minPeakVal": None,
      "unitsForDisplay": "%"
    }
  ],
  "autolog": False,
  "tadd": "12",
  "units": "IMPERIAL",
  "pressurePreference": "RELATIVE",
  "pressureUnits": "DEFAULT",
  "tempUnits": "DEFAULT",
  "speedUnits": "DEFAULT",
  "torqueUnits": "METRIC",
  "flowUnits": "METRIC"
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    